curdApp/urls.py
from . import views
from django.urls import path

app_name = "curd_app"

urlpatterns = [
    path("", views.retrieve, name="retrieve"),
    # path("create", views.create, name="create"),
    # path("movie/<int:movie_id>/", views.detail, name="detail"),
    # path("add/", views.add_movie, name="add_movie"),
    path("update/<int:id>/", views.update, name="update"),
    path("delete/<int:id>/", views.delete, name="delete"),
]

curd_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from curdApp import views

from curd_project import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("curdApp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curdApp/models.py
from django.db import models


# Create your models here.
class Data(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    SINO = models.IntegerField()

    def __str__(self):
        return self.name

curdApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Data

# from .forms import detailsform
from django.contrib import messages


# Create your views here.
def retrieve(request):
    data = Data.objects.all()
    if request.method == "POST":
        name = request.POST.get("name")
        desc = request.POST.get("desc")
        si_no = request.POST.get("SINO")
        detail = Data(name=name, desc=desc, SINO=si_no)
        detail.save()
        messages.info(request, "Data added successfully")
    context = {"data_list": data}

    return render(request, "retrieve.html", context)


# def create(request):
#     if request.method == "POST":
#         name = request.POST.get("name")
#         desc = request.POST.get("desc")
#         si_no = request.POST.get("SINO")
#         detail = Data(name=name, desc=desc, SINO=si_no)
#         detail.save()
#     return render(request, "retrieve.html")


def update(request, id):
    data = get_object_or_404(Data, id=id)

    # data = Data.objects.get(id=id)
    # form = detailsform(request.POST or None, request.FILES, instance=data)
    # if data.is_valid():
    #     name = request.POST.get("name")
    #     desc = request.POST.get("desc")
    #     si_no = request.POST.get("SINO")
    #     data = Data(name=name, desc=desc, SINO=si_no)
    #     data.save()
    if request.method == "POST":
        if (
            request.POST.get("name")
            and request.POST.get("desc")
            and request.POST.get("SINO")
        ):
            Data.objects.filter(id=id).update(
                name=request.POST.get("name"),
                desc=request.POST.get("desc"),
                SINO=request.POST.get("SINO"),
            )
        return redirect("/")
    messages.success(request, "The item was successfully updated")
    return render(request, "update.html", {"data": data})


def delete(request, id):
    if request.method == "POST":
        data = Data.objects.get(id=id)
        data.delete()
        return redirect("/")
    return render(request, "delete.html")


# ef editpost(request, id):
#         postobj= get_object_or_404(Post, id=id)

#         if request.method == 'POST':
#             if request.POST.get('title') and request.POST.get('content'):
#                 Post.objects.filter(id = id).update(title= request.POST.get('title'), content= request.POST.get('content'))

# 		messages.success(request, "The post was successfully updated")

#                 context={'postobj': postobj}


#                 return render(request, 'posts/edit.html')


#         else:
#                 context={'postobj': postobj,
# 			 'error': 'The post was not successfully updated. The title and content must be filled out.'}
#                 return render(request,'posts/edit.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'add.css' %}" />
    <link rel="stylesheet" href="{% static 'update.css' %}" />
    <link rel="stylesheet" href="{% static 'delete.css' %}" />
    <!-- Latest compiled and minified CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% block content %}
    <!-- content -->
    {% endblock %}
  </body>
</html>

templates/delete.html
{% extends 'base.html' %} {% block content %}
<div id="card" class="animated fadeIn">
  <div id="upper-side">
    <svg
      version="1.1"
      id="checkmark"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      x="0px"
      y="0px"
      xml:space="preserve"
    >
      <path
        d="M120.583 111.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"
      />
      <circle
        fill="none"
        stroke="#ffffff"
        stroke-width="5"
        stroke-miterlimit="10"
        cx="109.486"
        cy="104.353"
        r="32.53"
      />
    </svg>
    <h3 id="status">Success</h3>
  </div>
  <div id="lower-side">
    <p id="message">Are you delete this Movie</p>
    <form method="post">
      {% csrf_token %}
      <button id="contBtn">Continue</button>
    </form>
  </div>
</div>
{% endblock%}

templates/index.html
{% extends 'base.html' %} {% block content %}
<!-- <div class="container">
      <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Navbar</span>
      </nav>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input
            type="email"
            class="form-control"
            id="exampleInputEmail1"
            aria-describedby="emailHelp"
            placeholder="Enter email"
          />
          <small id="emailHelp" class="form-text text-muted"
            >We'll never share your email with anyone else.</small
          >
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input
            type="password"
            class="form-control"
            id="exampleInputPassword1"
            placeholder="Password"
          />
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
       Content here -->
<!--</div> -->
<nav class="navbar navbar-light bg-color">
  <a class="navbar-brand mx-auto bold" href="#">SIMPLE CURD OPERATION</a>
</nav>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <!-- Default form -->

      <!-- Horizontal form -->
      <form action="/" method="POST" class="form-horizontal pad-bg">
        {% csrf_token %}
        <div class="form-group">
          <label for="SINO" class="control-label col-sm-3">SI NO :</label>
          <div class="col-sm-9 mb-4">
            <input type="text" class="form-control input-lg" name="SINO" />
          </div>
        </div>
        <div class="form-group">
          <label for="name" class="control-label col-sm-3">Item name :</label>
          <div class="col-sm-9 mb-4">
            <input type="text" class="form-control input-lg" name="name" />
          </div>
        </div>
        <div class="form-group">
          <label for="desc" class="control-label col-sm-3">Description :</label>
          <div class="col-sm-9 mb-4">
            <input type="text" class="form-control input-lg" name="desc" />
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9 mt-4">
            <button class="btn btn-success">Create</button>
          </div>
        </div>
      </form>

      <div class="container">
        {% for message in messages %}
        <div class="alert alert-success">
          <strong>{{message}}</strong>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/retrieve.html
{% include 'index.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item name</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for i in data_list %}
          <tr>
            <th scope="row">{{i.SINO}}</th>
            <td>{{i.name}}</td>
            <td>{{i.desc}}</td>
            <td>
              <a class="btn btn-danger" href="{%  url 'curd_app:delete' i.id %}"
                >Delete</a
              >
            </td>
            <td>
              <a
                class="btn btn-success"
                href="{%  url 'curd_app:update' i.id %}"
                role="button"
                >Update</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %} {% block content %}
<nav class="navbar navbar-light bg-color">
  <a class="navbar-brand mx-auto bold" href="#">SIMPLE CURD OPERATION</a>
</nav>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <!-- Default form -->

      <!-- Horizontal form -->
      <form
        action="/update/{{data.id}}/"
        method="POST"
        class="form-horizontal pad-bg"
      >
        {% csrf_token %}
        <div class="form-group">
          <label class="control-label col-sm-3">SI NO :</label>
          <div class="col-sm-9 mb-4">
            <input
              type="text"
              class="form-control input-lg"
              value="{{data.SINO}}"
              name="SINO"
            />
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Item name :</label>
          <div class="col-sm-9 mb-4">
            <input
              type="text"
              class="form-control input-lg"
              value="{{data.name}}"
              name="name"
            />
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Description :</label>
          <div class="col-sm-9 mb-4">
            <input
              type="text"
              class="form-control input-lg"
              value="{{data.desc}}"
              name="desc"
            />
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9 mt-4">
            <button class="btn btn-success">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}